[package]
name = "vector"
version = "0.4.0-dev"
authors = ["Vector Contributors <vector@timber.io>"]
edition = "2018"
description = "A High-Performance Logs, Metrics, and Events Router"
homepage = "https://vector.dev"
license-file = "LICENSE"
readme = "README.md"
publish = false

[profile.bench]
debug = true

[package.metadata.deb]
section = "utility"
maintainer-scripts = "distribution/debian/scripts/"
conf-files = ["/etc/vector/vector.toml"]
assets = [
  ["target/release/vector", "/usr/bin/", "755"],
  ["config/vector.toml", "/etc/vector/vector.toml", "644"],
  ["config/vector.spec.toml", "/etc/vector/vector.spec.toml", "644"],
  ["config/examples/complete/*", "/etc/vector/examples/complex/", "644"],
  ["config/examples/sources/*", "/etc/vector/examples/sources/", "644"],
  ["config/examples/transforms/*", "/etc/vector/examples/transforms/", "644"],
  ["config/examples/sinks/*", "/etc/vector/examples/sinks/", "644"],
  ["distribution/systemd/vector.service", "/etc/systemd/system/vector.service", "644"]
]

[workspace]
members = [
  ".",
  "lib/codec",
  "lib/file-source",
  "lib/journald",
  "lib/tracing-metrics",
  "lib/tracing-limit",
]

[dependencies]
# Internal libs
codec = { path = "lib/codec" }
file-source = { path = "lib/file-source" }
journald = { path = "lib/journald" }
tracing-metrics = { path = "lib/tracing-metrics" }
tracing-limit = { path = "lib/tracing-limit" }

# Tokio / Futures
futures = "0.1.25"
tokio = { version = "0.1.22", features = ["io", "uds", "tcp", "rt-full", "experimental-tracing"], default-features = false }
tokio-retry = "0.2.0"
tokio-signal = "0.2.7"
tokio-threadpool = "0.1.16"
tokio-tls = "0.2.1"

# Tracing
tracing = "0.1.9"
tracing-futures = "0.0.1-alpha.1"
tracing-subscriber = "0.1.3"
tracing-log = "0.1.0"
tracing-tower = { git = "https://github.com/tokio-rs/tracing" }


# Metrics
hotmic = "0.8"

# Aws
rusoto_core = "0.37.0"
rusoto_s3 = "0.37.0"
rusoto_logs = "0.37.0"
rusoto_cloudwatch = "0.37.0"
rusoto_kinesis = "0.37.0"
rusoto_credential = "0.16.0"

# Tower
tower = "0.1.1"
tower-hyper = "0.1"

# Serde
serde = { version = "1.0.80", features = ["derive"] }
serde_json = "1.0.33"

# Prost
prost = "0.5"
prost-derive = "0.5"
prost-types = "0.5"

# External libs
atty = "0.2"
derivative = "1.0"
chrono = "0.4.6"
rand = "0.5.5"
regex = "1.0.5"
bytes = { version = "0.4.10", features = ["serde"] }
stream-cancel = "0.4.3"
prometheus = "0.4.2"
hyper = "0.12.18"
hyper-tls = "0.3.1"
native-tls = "0.2.3"
openssl = "0.10.25"
openssl-probe = "0.1.2"
string_cache = "0.7.3"
flate2 = "1.0.6"
structopt = "0.2.16"
indexmap = {version = "1.0.2", features = ["serde-1"]}
http = "0.1.14"
typetag = "0.1"
toml = "0.4"
syslog_rfc5424 = "0.6.1"
tokio-uds = "0.2.5"
derive_is_enum_variant = "0.1.1"
leveldb = { version = "0.8.4", optional = true }
db-key = "0.0.5"
headers = "0.2.1"
rdkafka = { version = "0.20.0", features = ["ssl"], optional = true }
hostname = "0.1.5"
seahash = "3.0.6"
jemallocator = { version = "0.3.0", optional = true }
lazy_static = "1.3.0"
rlua = "0.16.3"
num_cpus = "1.10.0"
bytesize = "1.0.0"
grok = "1.0.0"
nom = "5.0.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
exitcode = "1.1.2"
snafu = "0.4.3"
url = "1.7"
base64 = "0.10.1"
shiplift = { git = "https://github.com/LucioFranco/shiplift", branch = "timber" }
owning_ref = "0.4.0"

[build-dependencies]
prost-build = "0.4.0"
built = "0.3"

[dev-dependencies]
approx = "0.3.0"
criterion = "0.2.5"
reqwest = "0.9.5"
tempfile = "3.0.6"
libc = "0.2.43"
walkdir = "2.2.7"
elastic = { git = "https://github.com/elastic-rs/elastic" }
matches = "0.1.8"
pretty_assertions = "0.6.1"
proptest = "0.9"
tokio01-test = "0.1.1"
tower-test = "0.1"

[features]
default = ["rdkafka", "leveldb", "jemallocator"]
docker = [
  "cloudwatch-logs-integration-tests",
  "cloudwatch-metrics-integration-tests",
  "clickhouse-integration-tests",
  "es-integration-tests",
  "kafka-integration-tests",
  "kinesis-integration-tests",
  "s3-integration-tests",
  "splunk-integration-tests",
  "docker-integration-tests"
]
cloudwatch-logs-integration-tests = []
cloudwatch-metrics-integration-tests = []
clickhouse-integration-tests = []
es-integration-tests = []
kafka-integration-tests = []
kinesis-integration-tests = []
s3-integration-tests = []
splunk-integration-tests = []
docker-integration-tests = []

[[bench]]
name = "bench"
harness = false
